### PR TITLE
Add linking to Terraform documentation (#113)

### PR DESCRIPTION
**Pull request by matthew16550**
The "View External Documentation" and "Navigate Declaration" actions both open documentation in the browser for:

 * backends
 * data sources
 * keywords
 * functions
 * providers
 * provisioners
 * resources

Beware this is my first use of Kotlin and my first IntelliJ plugin so I wont be surprised if there are some silly mistakes!

### CODE REVIEW

**Comment by G-Rath** [comment]
@VladRassokhin any chance of this getting reviewed? Would love to have this feature, as it's pretty much the main thing missing vs what the Code plugin offers 🙂

**Comment by ajorpheus** [comment]
v 0.7.3 just added this: https://plugins.jetbrains.com/plugin/7808-hashicorp-terraform--hcl-language-support

> Support external documentation in 'Quick Documentation' action for Terraform providers, resources and data sources

It is far from being as usable as the VS Code implementation. When the feature appeared on the change log I assumed this fork had been merged in but apparently not.

**Comment by matthew16550** [comment]
@VladRassokhin I'm keen to help with this but not sure if I can now that the source is closed?

**Comment by VladRassokhin** [comment]
For now I’ve implemented much simpler feature which just provides link to official documentation for resources and providers. It’s done for several reasons: 

* Much faster to implement
* Don’t increase distribution size and memory consumption. Even simpler [terraform-metadata](https://github.com/VladRassokhin/terraform-metadata) is 0.5 MiB compressed and consumes around 5 MiB in IDE memory with all possible deduplications performed. 
* From legal perspective I’m not sure about scrubbing documentation and bundling it with plugin. However same applies for terraform-metadata, but it’s done from MPL-licensed sources.

@matthew16550 I do appreciate what’ve you done in this PR, though for now I don’t have enough time to thorough review code and implement something similar based on your code.

**Pull request closed without merging**
