### PR TITLE
Add tags property to aws_kinesis_firehose_delivery_stream

### PR DESCRIPTION
**Pull request by pgilad**
See https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html#tags

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Thank for your time, yet unfortunately I cannot accept this PR since all files in `res/terraform/model/providers/` are generated from provider sources and updated just before releasing new plugin version.

**Comment by pgilad** [comment]
Oh I see, silly me! thanks!

**Comment by VladRassokhin** [comment]
That's ok, sorry for wasting your time, probably I should put some warning or completely move those generated files out of this repository

**Comment by VladRassokhin** [comment]
No. Quite rarely I'd say, lately. Hopefully it would change in Jan-Feb, I'm already working on automating solution for this.

**Pull request closed without merging**
